services:
  postgres_local_db:
    image: postgres:latest
    container_name: workshop-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: newDB
